Iter1
renatus-cartesius/gophermart pull request #1
Opened 2024-12-24 01:23 UTC by renatus-cartesius

2024-12-28 15:32 UTC, bulbetski requested changes
Написано хорошо, в основном замечания по код стайлу и стуруктуре проекта

2024-12-28 15:32 UTC, bulbetski commented on cmd/gophermart/main.go
> +		DBDSN:      "host=pg-db user=gophermart_owner password=dummy dbname=gophermart sslmode=disable",
из энвы надо брать

2024-12-28 15:32 UTC, bulbetski commented on cmd/gophermart/main.go
> +	}
сделай для этого всего хэлпер, чтобы не засорять мэйн (хэлпер в самом мейне)

2024-12-28 15:32 UTC, bulbetski commented on cmd/gophermart/main.go
> +		}()
По идее это избыточно, так как server.Shutdown уже обрабатывает таймаут через переданный контекст

2024-12-28 15:32 UTC, bulbetski commented on cmd/gophermart/main.go
> +	serverCtx, serverStopCtx := context.WithCancel(context.Background())
Ты создаешь serverCtx и serverStopCtx, но они фактически не используются для управления жизненным циклом приложения.
Их можно убрать что ли или как-то использовать

2024-12-28 15:32 UTC, bulbetski commented on cmd/gophermart/migrations/20241217221934_orders.sql
> +SELECT 'down SQL query';
можно убрать

2024-12-28 15:32 UTC, bulbetski commented on cmd/gophermart/migrations/20241217221947_users.sql
> +SELECT 'down SQL query';
можно убрать

2024-12-28 15:32 UTC, bulbetski commented on cmd/gophermart/migrations/20241217221934_orders.sql
> +    uploaded timestamp
Даты можно сделать либо default current_timestamp, либо default now()
Так же для дат стоит использовать WITH TIMEZONE, потому что если будет происходить какая-то конвертация времени с учетом таймзоны в коде, то время будет втупую прибавляться или отниматься от таймстеймпа, в котором таймзоны нет

2024-12-28 15:32 UTC, bulbetski commented on cmd/gophermart/migrations/20241217221947_users.sql
> +DROP TABLE IF EXISTS users CASCADE;
Мигация должна откатывать только то, что создала. Каскад может поудалять много чего ваще. Просто drop table users

2024-12-28 15:32 UTC, bulbetski commented on cmd/gophermart/migrations/20241217221954_withdrawals.sql
> +SELECT 'down SQL query';
Убрать каскад и селект

2024-12-28 15:32 UTC, bulbetski commented on internal/auth/auth.go
> +	RegistrateUser(ctx context.Context, ar *AuthRequest) (string, error)
register*

2024-12-28 15:32 UTC, bulbetski commented on internal/auth/auth.go
> +	if !userExists || strings.Compare(string(passwordHash), realpasswordHash) == 0 {
Для проверки нужно использовать bcrypt.CompareHashAndPassword

2024-12-28 15:32 UTC, bulbetski commented on internal/auth/auth.go
> +type Auth struct {
Вообще по структуре приложения. Можно сделать пакет репозитория, внутри которого будут все-все методы, которые взаимодействуют с бд. Разбить так же по файлам. По месту использования уже создать интерфейсы.

Итого у тебя handler/(auth, accrual и т.д.) -> service/(auth, accrual и т.д.) -> repository(auth, accrual и т.д.)

и всего получается 3 структуры вместо миллиона. Сами структуры уже внутри себя могут содержать сколько хочешь интерфейсов

2024-12-28 15:32 UTC, bulbetski commented on internal/auth/auth.go
> +	hashRow := a.db.QueryRowContext(ctx, "SELECT passwodHash from users where id = $1", ar.Login)
наверн опечатка в названии поля passwordHash

2024-12-28 15:32 UTC, bulbetski commented on internal/auth/auth.go
> +func (a *Auth) RegistrateUser(ctx context.Context, ar *AuthRequest) (string, error) {
В RegistrateUser и LoginUser токен создается одинаково, что можно вынести в отдельную функцию

2024-12-28 15:32 UTC, bulbetski commented on internal/loyalty/loyalty.go
> +	_, err := l.db.ExecContext(ctx, "INSERT INTO orders (id, userID, status, accrual, uploaded) VALUES ($1, $2, $3, $4, $5)", orderInfo.Order, userID, orderInfo.Status, orderInfo.Accrual, time.Now())
Запрос проверки существования заказа можно объединить с попыткой вставки, используя ON CONFLICT. 

```
query := `
		INSERT INTO orders (id, userID, status, accrual, uploaded)
		VALUES ($1, $2, $3, $4, $5)
		ON CONFLICT (id) DO NOTHING
	`
	
		rowsAffected, err := res.RowsAffected()
	if err != nil {
		logger.Log.Error("error checking rows affected", zap.Error(err))
		return err
	}

	if rowsAffected == 0 {
		return ErrOrderAlreadyUploaded
	}
```

2024-12-28 15:32 UTC, bulbetski commented on internal/loyalty/loyalty.go
> +func (l *Loyalty) Withdraw(ctx context.Context, wr *WithdrawRequest) error {
Это надо выполнять в транзакции, чтобы избежать гонок

2024-12-28 15:32 UTC, bulbetski commented on internal/loyalty/mocks.go
> +package loyalty
моки лучше положить в отдельный пакет mocks, либо назвать с _mock на конце, чтобы файл как тестовый выделялся

2024-12-28 15:32 UTC, bulbetski commented on internal/server/handlers/handlers.go
> +	w.Write(buf.Bytes())
как будто orders можно передать напрямую и не делать ничего с буффером

2024-12-28 15:32 UTC, bulbetski commented on internal/server/handlers/handlers.go
> +	userID := r.Context().Value("userID").(string)
для всех хттп аргументов во всех методах нужно добавить базовые валидации, чтобы в случае невалидности входных параметров возвращать BadRequest и не проваливаться дальше в код

2024-12-28 15:32 UTC, bulbetski commented on internal/server/middlewares/middlewares.go
> +package middlewares
лучше сделать пакет middleware и либо внутри него сделать по пакету для каждой из твоих мидлварь, либо просто разбить их на отдельные файлы

2024-12-28 15:32 UTC, bulbetski commented on internal/server/middlewares/middlewares.go
> +func (gw *gzipWriter) WriteHeader(statusCode int) {
можно этот метод убрать и сделать вместо него что-то подобное
```

func (gw *gzipWriter) Write(b []byte) (int, error) {
	if gw.Header().Get("Content-Encoding") == "" {
		gw.Header().Set("Content-Encoding", "gzip")
	}
	return gw.zw.Write(b)
}

func (gw *gzipWriter) Close() error {
	return gw.zw.Close()
}
```

2024-12-28 15:32 UTC, bulbetski commented on internal/server/models/models.go
> +type MetricsBatch []*Metric
выглядит, как что-то лишнее

2025-01-12 20:36 UTC, renatus-cartesius commented on internal/loyalty/loyalty.go
> +	_, err := l.db.ExecContext(ctx, "INSERT INTO orders (id, userID, status, accrual, uploaded) VALUES ($1, $2, $3, $4, $5)", orderInfo.Order, userID, orderInfo.Status, orderInfo.Accrual, time.Now())
Мне еще дополнительно нужно проверять пользователя, загрузившего заказ. Наверное это тоже можно на изи через на стороне SQL, но наверное оставлю пока так

2025-01-12 22:49 UTC, renatus-cartesius commented on internal/server/middlewares/middlewares.go
> +func (gw *gzipWriter) WriteHeader(statusCode int) {
WriteHeader нельзя убирать, т.к. тогда gzipWriter не будет имплементить http.ResponseWriter

2025-01-13 18:33 UTC, bulbetski approved these changes
Микроммент оставил, вместо структур as is лучше передавать интерфейсы, а так всё ок

2025-01-13 18:33 UTC, bulbetski commented on internal/server/handlers/handlers.go
> +	l *loyalty.Loyalty
заменить бы на интерфейс и использовать более описательное название

2025-01-13 19:37 UTC, merged